### ISSUE TITLE
Próximo passo

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-guia-de-servicos#42]
De acordo com o termo de recusa:
```
9.1 "É importante que a informação sobre como proceder no processo dessa solicitação " que processo? Da forma como estamos cadastrando o serviço não está intuitivo para o cadastrador que há um processo. O texto precisa ser melhorado, ou a forma de cadastrar cada passo.

9.2 "além de oferecer um link de para onde o cidadão deverá ir para continuar utilizando esse serviço": Não ficou claro. O cidadão quer obter o serviço de uma vez, como assim continuar utilizando?

9.3 considerando a necessidade de ter um detalhamento maior do passo­a­passo, este campo ficaria inútil.
```

**Comment by jeankirchner** [comment]
Percebemos que o campo próximo passo estava gerando uma confusão, mesmo para nós que temos o contexto do projeto, já optamos por remove-lo e estamos tratando esse assunto de uma forma mais ampla no passo a passo. Relacionado #41

**Comment by sahrosa** [comment]
Pessoal,
estamos fechando este cartão pois os pontos aqui comentados já foram tratados nos #20, #21, #25, #23. Estes pontos já não refletem mais no cenário atual.

Futuramente mais melhorias poderão ser feitas no #59.
