### ISSUE TITLE
Subproduto II.2 Observações gerais

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-guia-de-servicos#48]
Conforme termo de recusa:

1. Onde está a informação do canal?
2. Observações do decreto 6932, no cartão #49 
3. A ASEGE utiliza o termo “requerente” ao invés de “solicitante”. Há algum motivo para usar o termo “solicitante” ?
4. O termo passo do cadastro está conflitando com o termo passo do serviço.

**Comment by jeankirchner** [comment]
1. @mformiga, @almeidafab - podem complementar esse ponto? Podemos definir melhor o que é canal? Queremos uma separação de canais para atendimento, canal de prestação de serviço, ou são a mesma coisa?
2. De fato não consideramos esse decreto por completo no editor, mas já estávamos pensando em relação à carta de serviços, e como podemos gerar ela quando os serviços estiverem cadastrados com uma certa maturidade.
3. @sahrosa sabes sobre esse ponto?
4. Faz sentido, estamos pensando em utilizar "Etapa", para ter uma separação

**Comment by sahrosa** [comment]
Quanto ao ponto 3, utilizamos o termo "solicitante" para deixar um pouco menos impessoal do que "requerente". Se houver uma necessidade de voltar atrás, isso é uma mudança simples, mas acredito que quando usamos termos mais amigáveis como nesse caso, facilitaremos o preenchimento dos serviços :)

**Comment by almeidafab** [comment]
@jeankirchner 1. canal é o meio pelo qual o cidadão vai interagir com o Estado. Temos mapeados até o momento os seguintes canais: web, presencial, telefone, e-mail, postal, aplicativo móvel, SMS, TV Digital, Fax, rede social. Nós não fizemos essa separação, tratamos apenas como canal de prestação do serviço.

**Comment by cv** [comment]
Este cartão já foi destrinchado em outros, ou ainda temos algo específico que não foi contemplado em outros cartões? @jeankirschner?

**Comment by jeankirchner** [comment]
Além desse cartão, foi criado o #49 para tratar com o item 2, eu editei um pouco a descrição dele. Não há mais nada para adicionar nesse ou no #49.

**Comment by sahrosa** [comment]
* "Observações do decreto 6932" no cartão #49
* "A ASEGE utiliza o termo “requerente” ao invés de “solicitante”. Há algum motivo para usar o termo “solicitante”?" no cartão #56
* "Onde está a informação do canal?" no cartão #57 
* "O termo passo do cadastro está conflitando com o termo passo do serviço." resolvida no #25
