### ISSUE TITLE
Pontos do decreto 6932 não atendidos

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-guia-de-servicos#49]
Conforme termo de recusa:

> Art.11. Os órgãos e entidades do Poder Executivo Federal que prestam serviços diretamente ao cidadão deverão elaborar e divulgar “Carta de Serviços ao Cidadão”, no âmbito de sua esfera de competência.

> §2 A Carta de Serviços ao Cidadão deverá trazer informações claras e precisas em relação a cada um dos serviços prestados, em especial as relacionadas com:

> V ­ a forma de prestação do serviço; ** entendemos ser o canal, não está informado.

> VII ­ os locais e formas de acessar o serviço. ** entendemos ser o canal, não está informado.
§3 o Além das informações descritas no § 2o, a Carta de Serviços ao Cidadão deverá detalhar os padrões de qualidade do atendimento relativos aos seguintes aspectos:

> V ­ procedimentos para receber, atender, gerir e responder às sugestões e reclamações;** temos posteriormente que melhorar nosso feedback

> VI ­ fornecimento de informações acerca das etapas, presentes e futuras, esperadas para a realização dos serviços, inclusive estimativas de prazos; ** na nossa visão este item seria atendido pelo detalhamento dos passos, inclusive com prazos, custos e resultados dos passos.

**Comment by sahrosa** [comment]
@almeidafab, @mformiga - Comentamos cada ponto detalhadamente abaixo, mas gostaríamos de discutir: o decreto 6932 já se qualifica como um item do termo de recusa, considerando essa fase inicial do editor? 

Todos os itens abaixo serão tratados nos seus respectivos cartões, mas saber se fazem parte do termo de recusa ou não, é importante para priorizar os nossos esforços.

```V ­ a forma de prestação do serviço; ** entendemos ser o canal, não está informado.
VII ­ os locais e formas de acessar o serviço. ** entendemos ser o canal, não está informado.```

Estão sendo tratadas na issue #57

```V ­ procedimentos para receber, atender, gerir e responder às sugestões e reclamações;** temos posteriormente que melhorar nosso feedback``` - tratado no cartão #58
```VI ­ fornecimento de informações acerca das etapas, presentes e futuras, esperadas para a realização dos serviços, inclusive estimativas de prazos``` - tratado no cartão #59

**Comment by jeankirchner** [comment]
Cartão fechado, pois #57, #58, #59 foram abertos para resolver as questões desse.
