### ISSUE TITLE
Calendário do serviço

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-guia-de-servicos#54]
Pessoal,
fiquei pensando em função do SISU, se não podemos dar a opção de preencher no editor as datas importantes, como por exemplo:

* Período de inscrições - 08/06 a 10/06
* Resultado da chamada regular - 15/06
* Prazo para participar da Lista de Espera - 15/06 a 26/06
* Matrícula da chamada regular - 19/06 a 23/06
* Convocação dos candidatos em lista de espera - 02/07

Se tivermos essa informação isso poderá ser super útil para o cidadão que precisa se inscrever e portanto, saber das datas limite.  O que acham @mformiga @almeidafab?

**Comment by jeankirchner** [comment]
Só para clarificar, você sugere criar campos específicos para isso?

**Comment by sahrosa** [comment]
Sim, pelo menos para datas críticas como período de inscrição. Assim deixamos claro se o serviço está em período de inscrição, se ainda não começou ou se já passou.

**Comment by cv** [comment]
Acho que seria um problema para o órgão lembrar de atualizar estas datas todos os anos. Vamos esperar até ter um órgão com esse problema para conseguir feedback?

**Comment by mformiga** [comment]
Poderia ser um campo sazonal associado ao serviço. Só iria aparecer naquele período.

**Comment by almeidafab** [comment]
concordo com o @cv acredito que seria um problema para o órgão essa atualização de datas todo ano.

**Comment by sahrosa** [comment]
Fechando essa issue então! 

Aí pensamos em alguma forma de resolver isso de outra maneira. 

Acredito que datas são super importantes como informação básica do serviço, mas como isso não é a regra, pois nem todos os serviços tem esse tipo de data, podemos pensar nisso no futuro!
