### ISSUE TITLE
XSD -> HTML (formulário)

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-guia-de-servicos#7]
- [ ] Converte XSD do Modelo de Explicitação de Serviço em um formulário web
  - [ ] texto pequeno (input text)
  - [ ] texto longo (textarea)
  - [ ] escolha simples (dropdown)
  - [ ] múltipla escolha simples (checkboxes)
  - [ ] múltipla escolha para menos de 4 itens (radio)

Outros tipos de entrada em mais cartões no futuro.

**Comment by jeankirchner** [comment]
Considerando que estamos implementando o formulário na mão, isso aqui ainda está valendo?

**Comment by cv** [comment]
Acho que não mais - implementar o formulário em HTML puro nos dá bem mais flexibilidade, dadas as regras de validação, previews etc que vêm aparecendo.
